### ISSUE TITLE
504: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by adityarizqi** [Zhirrr/ceramah-rest-api-indonesia#1]
API Timeout, untuk APInya ada yang error bang, buat BASE URL gak ada masalah, pas pake yang input query dia pasti BAD GATEWAY

-No Problem (response JSON)
https://ceramah-api-zhirrr.vercel.app/api/ustadz/search?q=

-Problem
https://ceramah-api-zhirrr.vercel.app/api/ustadz/search?q=Ustadz%20Abdul%20Somad

**Comment by Zhirrr** [comment]
Oke, ntar ane fix insya Allah

**Comment by adityarizqi** [comment]
> Oke, ntar ane fix insya Allah

Ane coba masih blm work gan linknya.. blm di update ya gan..
